### ISSUE TITLE
Rails 5, Devise 4.2.0 "undefined method" errors from config in devise.rb

### ISSUE THREAD

**Issue by gbrl** [Houdini/two_factor_authentication#101]
I'm having an issue with 3 config options in my app. The following 3 config options cause "undefined method..." errors:
```
config.direct_otp_valid_for
config.direct_otp_length
config.second_factor_resource_id
```
Commenting out those three lines in my devise.rb initializer file allows the app to start, but I'm not sure if this breaks anything. Will look into it further.

Here's the full error message I get when starting the server:

```
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/dude/Work/myapp/config/initializers/devise.rb:338:in `block in <top (required)>': undefined method `second_factor_resource_id=' for Devise:Module (NoMethodError)
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/devise-4.2.0/lib/devise.rb:292:in `setup'
	from /Users/dude/Work/myapp/config/initializers/devise.rb:3:in `<top (required)>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/engine.rb:647:in `load_config_initializer'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `each'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `each'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/dude/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/dude/Work/myapp/config/environment.rb:5:in `<top (required)>'
	from /Users/dude/Work/myapp/config.ru:3:in `require_relative'
	from /Users/dude/Work/myapp/config.ru:3:in `block in <main>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/dude/Work/myapp/config.ru:in `new'
	from /Users/dude/Work/myapp/config.ru:in `<main>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/dude/Work/myapp/bin/rails:9:in `require'
	from /Users/dude/Work/myapp/bin/rails:9:in `<top (required)>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /Users/dude/.rvm/gems/ruby-2.2.2/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/dude/Work/myapp/bin/spring:13:in `require'
	from /Users/dude/Work/myapp/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Any ideas? Or advice?

Thanks for your time!

**Comment by gbrl** [comment]
I used the github repo in my Gemfile an these errors went away.
