### ISSUE TITLE
uninitialized constant Devise::VERSION

### ISSUE THREAD

**Issue by pstaender** [Houdini/two_factor_authentication#116]
Hi,

first thanks for making this great gem :)

After resetting `cookies.signed[TwoFactorAuthentication::REMEMBER_TFA_COOKIE_NAME]` the `Devise::TwoFactorAuthenticationController#update` produces the exception `uninitialized constant Devise::VERSION` in line 33 `if Devise::VERSION.to_f >= 4.2`. I'm using Rails 5 and Devise 4.2.0.

Trace:
```
/bundle/bundler/gems/two_factor_authentication-40fb11b069ddcontrollers/devise/two_factor_authentication_controller.rb:33:in `after_two_factor_success_for'
/bundle/bundler/gems/two_factor_authentication-40fb11b069ddcontrollers/devise/two_factor_authentication_controller.rb:14:in `update'
actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
...
```

PR with fix: https://github.com/Houdini/two_factor_authentication/pull/115

**Comment by pstaender** [comment]
merged https://github.com/Houdini/two_factor_authentication/pull/115
