### ISSUE TITLE
Rails 8 incompatability

### ISSUE THREAD

**Issue by jasonperrone** [Houdini/two_factor_authentication#216]
```
ArgumentError: :only and :except must include only [:show, :create, :update, :destroy, :new, :edit], but also included [:resend_code]
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1184:in `initialize'
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1287:in `initialize'
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1356:in `new'
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1356:in `block in resource'
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1836:in `with_scope_level'
    actionpack (8.0.1) lib/action_dispatch/routing/mapper.rb:1354:in `resource'
    two_factor_authentication (da1c6aa8e499) lib/two_factor_authentication/routes.rb:6:in `devise_two_factor_authentication'
```

Seems to be related to this Rails 8 change:
Raise an ArgumentError when invalid :only or :except options are passed into #resource and #resources

**Comment by jon-sully** [comment]
FYI this monkey patch got things working for me:

```ruby
# ~/config/initializers/two_factor_authentication.rb

module ActionDispatch::Routing
  class Mapper
    protected

      def devise_two_factor_authentication(mapping, controllers)
        resource :two_factor_authentication, only: [:show, :update], path: mapping.path_names[:two_factor_authentication], controller: controllers[:two_factor_authentication] do
          # Define the resend_code route explicitly, without including it in :only above
          collection { get "resend_code" }
        end
      end
  end
end
```

99% clone of the original code (10 years old, now) just tweaks the `only: [:show, :update]` chunk

**Comment by pioz** [comment]
Same problem here.

**Comment by pioz** [comment]
Any ETA on this?

**Comment by jon-sully** [comment]
FYI: https://github.com/Houdini/two_factor_authentication/issues/193
