### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dahal** [Houdini/two_factor_authentication#57]
Hello,

These configurations, should they go to rails `application.rb` `environment.rb` or `devise.rb`

```ruby
config.max_login_attempts = 3  # Maximum second factor attempts count
config.allowed_otp_drift_seconds = 30  # Allowed time drift
config.otp_length = 6  # OTP code length
config.remember_otp_session_for_seconds = 30.days  # Time before browser has to enter OTP code again
```

**Comment by Houdini** [comment]
Hello, this should go to devise.rb.
A'll add that to README.

Thanks

**Comment by dahal** [comment]
I may be missing something, but this is the error i get if I add that on my `devise.rb`

```ruby
/Users/dahal/MyApp/config/initializers/devise.rb:8:in `block in <top (required)>': undefined method `remember_otp_session_for_seconds=' for Devise:Module (NoMethodError)
	from /Users/dahal/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/devise-3.5.2/lib/devise.rb:278:in `setup'
	from /Users/dahal/MyApp/config/initializers/devise.rb:3:in `<top (required)>'
```

**Comment by fabioglopes** [comment]
Same issue here.

**Comment by rutgerg** [comment]
Same issue here.

**Comment by Houdini** [comment]
Please, use version 1.1.4
It should work
